site_name: Richard Chou
plugins:
  - blog:
      draft_if_future_date: true
      draft: false
      archive: false
  - search
nav:
  - Blog:
    - blog/index.md
  - about-me.md
theme:
  name: material
  logo: assets/images/richardchou-small.png
  features:
    - navigation.instant
    - navigation.indexes
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: orange
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
site_url: https://konami99.github.io/
